<a href="https://colab.research.google.com/github/JWasonga/Statistical_Data_Analytics/blob/Applied_Statistics_and_Econometrics-_Portfolio/2_data_cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Mushroom Edibility - Data Cleaning & Feature Engineering

Pipeline:

   1. Encode `class` (e->0, p->1)
   2. Replace '?' in `stalk_root` with a new "missing" category (preserves the missingness signal)
   3. Drop the constant columns(s) (`veil_type`)
   4. One-hot encode all remaining categorical features (`drop_first=True`)
   5. Save to `data/mushrooms_cleaned.csv`

#1. Imports & Load Raw Data

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import sys
sys.path.append(".")
from utils import (load_data, encode_target, handle_missing, drop_constant, preprocess_data)

sns.set_style("whitegrid")
plt.rcParams["figure.figsize"] = (10, 6)

%matplotlib inline

In [3]:
df = load_data("mushrooms.csv")
print(f"Raw Shape: {df.shape}")
df.head()

Raw Shape: (8124, 23)

  class cap_shape cap_surface  ... spore_print_color population habitat
0     p         x           s  ...                 k          s       u
1     e         x           s  ...                 n          n       g
2     e         b           s  ...                 n          n       m
3     p         x           y  ...                 k          s       u
4     e         x           s  ...                 n          a       g

[5 rows x 23 columns]

#2. Missing / Invalid Values

The UCI dataset uses `'?'` to mark missing `stalk_root` values

In [4]:
missing_marker = (df == "?").sum()
print(missing_marker[missing_marker > 0])
print(f"\nDuplicate rows:  {df.duplicated().sum()}")

stalk_root    2480
dtype: int64

Duplicate rows:  0

#3. Encode Target

In [5]:
df_enc = encode_target(df)
print("Class distribution:")
print(df_enc["class"].value_counts())
df_enc.head()

Class distribution:
class
0    4208
1    3916
Name: count, dtype: int64

   class cap_shape cap_surface  ... spore_print_color population habitat
0      1         x           s  ...                 k          s       u
1      0         x           s  ...                 n          n       g
2      0         b           s  ...                 n          n       m
3      1         x           y  ...                 k          s       u
4      0         x           s  ...                 n          a       g

[5 rows x 23 columns]

#4. Handle Missing Values

We treat missing `stalk_root` as it's own category (`m`issing`) rather than imputing - the missingness itself may carry signal.

In [6]:
df_filled = handle_missing(df_enc, strategy="category")
print("After replacing '?' with 'missing' :")
print(df_filled["stalk_root"].value_counts())

After replacing '?' with 'missing' :
stalk_root
b          3776
missing    2480
e          1120
c           556
r           192
Name: count, dtype: int64

#5. Drop Constant Columns

In [7]:
df_no_const, dropped = drop_constant(df_filled)
print(f"Dropped columns (constant): {dropped}")
print(f"Shape after dropping constant columns: {df_no_const.shape}")

Dropped columns (constant): ['veil_type']
Shape after dropping constant columns: (8124, 22)

#6. Distribution Check Pre/Post Encoding

In [8]:
cat_cols = [c for c in df_no_const.columns if c != "class" and df_no_const[c].dtype == object]
print(f" Will one-hot encode  {len(cat_cols)} categorical columns")
print(f"   -> total dummy columns:",
      sum(df_no_const[c].nunique() - 1 for c in cat_cols))

 Will one-hot encode  21 categorical columns
   -> total dummy columns: 95

#7. Run the Full Pipeline

In [9]:
df_processed = preprocess_data(df, missing_strategy="category")
print(f"Processed shape: {df_processed.shape}")
print(f"Missing values: {df_processed.isnull().sum().sum()}")
df_processed.head()

Processed shape: (8124, 96)
Missing values: 0

   class  cap_shape_c  cap_shape_f  ...  habitat_p  habitat_u  habitat_w
0      1            0            0  ...          0          1          0
1      0            0            0  ...          0          0          0
2      0            0            0  ...          0          0          0
3      1            0            0  ...          0          1          0
4      0            0            0  ...          0          0          0

[5 rows x 96 columns]

#8. Sanity Checks & Save

In [10]:
assert df_processed["class"].isin([0, 1]).all()
assert df_processed.isnull().sum().sum() == 0
assert "veil_type" not in df_processed.columns
print("All checks passed.")

All checks passed.

In [11]:
df_processed.to_csv("mushrroms_cleaned.csv", index=False)
print(f"Saved to data/mushrooms_cleaned.csv ({df_processed.shape[0]} rows, {df_processed.shape[1]} cols)")

Saved to data/mushrooms_cleaned.csv (8124 rows, 96 cols)